export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';

export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const FETCH_MESSAGE_FAILURE = `${FETCH_MESSAGE}_${FAILURE}`;
export const FETCH_MESSAGE_SUCCESS = `${FETCH_MESSAGE}_${SUCCESS}`;

export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_IN_USER_FAILURE = `${SIGN_IN_USER}_${FAILURE}`;
export const SIGN_IN_USER_SUCCESS = `${SIGN_IN_USER}_${SUCCESS}`;

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_FAILURE = `${SIGN_UP_USER}_${FAILURE}`;
export const SIGN_UP_USER_SUCCESS = `${SIGN_UP_USER}_${SUCCESS}`;

export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const SIGN_OUT_USER_SUCCESS = `${SIGN_OUT_USER}_${SUCCESS}`;
